package com.example.racing_game.service;

import com.example.racing_game.domain.PrizePool;
import com.example.racing_game.domain.User;
import com.example.racing_game.domain.UserCar;
import com.example.racing_game.repository.PrizePoolRepository;
import com.example.racing_game.repository.UserCarRepository;
import com.example.racing_game.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;


@Service
@RequiredArgsConstructor
public class CarService {

    private final UserRepository userRepository;
    private final UserCarRepository userCarRepository;
    private final PrizePoolRepository prizePoolRepository;

    private static final long ENTRY_FEE_PER_CAR = 50000L;

    @Transactional
    public void registerCars(String username, int quantity) {
        if (quantity <= 0) {
            throw new IllegalArgumentException("최소 1대 이상 등록해야 합니다.");
        }

        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UsernameNotFoundException("사용자를 찾을 수 없습니다."));

        long totalCost = quantity * ENTRY_FEE_PER_CAR;
        if (user.getBalance() < totalCost) {
            throw new IllegalArgumentException("잔액이 부족합니다! (필요: " + totalCost + "원)");
        }

        user.setBalance(user.getBalance() - totalCost);

        PrizePool prizePool = prizePoolRepository.findById(1L)
                .orElseGet(() -> prizePoolRepository.save(new PrizePool()));
        prizePool.setAmount(prizePool.getAmount() + totalCost);

        long currentCarCount = userCarRepository.countByOwner(user);

        for (int i = 1; i <= quantity; i++) {
            long carNumber = currentCarCount + i;
            String autoGeneratedName = username + "_" + carNumber;

            UserCar newCar = new UserCar(autoGeneratedName, user);
            userCarRepository.save(newCar);
        }
    }
}